from __future__ import annotations

VIEW_DASH = "VIEW_DASH"
VIEW_MARKET = "VIEW_MARKET"
VIEW_POLICIES = "VIEW_POLICIES"
VIEW_INDUSTRY = "VIEW_INDUSTRY"
VIEW_HISTORY = "VIEW_HISTORY"
EXPLAIN = "EXPLAIN"
HELP = "HELP"
QUIT = "QUIT"
ENACT_POLICY = "ENACT_POLICY"
LANG = "LANG"
UNLOCK_LIST = "UNLOCK_LIST"
SHOW_GOALS = "SHOW_GOALS"
INTEL = "INTEL"

VIEW_INTENTS = {VIEW_DASH, VIEW_MARKET, VIEW_POLICIES, VIEW_INDUSTRY, VIEW_HISTORY, EXPLAIN}
